name: Maven build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    if: github.repository_owner == 'internetpolice-eu'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Cache Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn -U clean deploy

      # Mark our scripts runnable:
      - name: Mark deploy scripts runnable
        if: ${{ github.event_name == 'push' }}
        run: |
          chmod +x "${GITHUB_WORKSPACE}/.github/deploy-staging.sh"
          chmod +x "${GITHUB_WORKSPACE}/.github/deploy-release.sh"
          
      # Deploy from master branch (staging release):
      - name: Run deploy script for staging release
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: "${GITHUB_WORKSPACE}/.github/deploy-staging.sh"

      # Deploy from tag create (plugin release):
      - name: Run deploy script for plugin release
        if: ${{ github.event_name == 'push' && startsWith( github.ref, 'refs/tags/') }}
        run: "${GITHUB_WORKSPACE}/.github/deploy-release.sh"